- arg: extension-pkg-whitelist
  val: islpy

- arg: ignore
  val:
  - compyte

- arg: ignored-modules
  val:
  - IPython
  - pycuda
  - maptlotlib
  - maptlotlib.pyplot

- arg: init-hook
  val: import sys; sys.setrecursionlimit(5000)

- arg: disable
  val:
  - E1102
