name: test-conda-env
channels:
- conda-forge
- defaults

dependencies:
- python=3
- git
- conda-forge::numpy
- pocl
- mako
- pyopencl
- islpy

# Only needed to make pylint succeed
- matplotlib
- ipykernel
- ply

- pip

- pip:
    - git+https://github.com/inducer/pytools.git
    - git+https://github.com/inducer/cgen.git
    - git+https://github.com/inducer/pymbolic.git
    - git+https://github.com/inducer/genpy.git
    - git+https://github.com/inducer/codepy.git
    - git+https://github.com/inducer/f2py
