name: test-conda-env
channels:
- conda-forge
- nodefaults

dependencies:
- python=3
- git
- numpy
- pocl
- mako
- pyopencl
- islpy

# Only needed to make pylint succeed
- matplotlib-base
- ipykernel
- ply
